name: CI workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
  lint:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Flake8
        run: pip install flake8

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 service --count --max-complexity=10 --max-line-length=127 --statistics
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.9-slim

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install nose  # Ensure Nose is installed

      - name: Run unit tests with Nose
        run: nosetests -v --with-spec --spec-color --with-coverage --cover-package=app
